name: Lidar Scan
options:
  developmentLanguage: en
  bundleIdPrefix: com.igorgoncharenko
  deploymentTarget:
    iOS: "18.0"
settings:
  base:
    DEVELOPMENT_TEAM: DW65K3AAUJ
    SWIFT_VERSION: "5.0"
targets:
  "Lidar Scan":
    type: application
    platform: iOS
    sources:
      - path: Lidar Scan
        excludes:
          - Preview Content
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: "Lidar Scan/Info.plist"
        PRODUCT_NAME: "Lidar Scan IGORAN"
        PRODUCT_BUNDLE_IDENTIFIER: com.igorgoncharenko.lidarscan
        INFOPLIST_KEY_CFBundleDisplayName: "Igor G-LIDAR"
        INFOPLIST_KEY_NSCameraUsageDescription: "Камера нужна для съёмки объекта или помещения и построения 3D‑модели с помощью LiDAR."
        INFOPLIST_KEY_NSMotionUsageDescription: "Датчики движения (гироскоп и акселерометр) нужны, чтобы точно отслеживать положение iPhone в пространстве при 3D‑сканировании."
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Геолокация используется только для компаса (север), чтобы стабильнее ориентировать 3D‑скан в пространстве."
        INFOPLIST_KEY_LSSupportsOpeningDocumentsInPlace: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_ENTITLEMENTS: Lidar Scan/Lidar_Scan.entitlements
    entitlements:
      path: Lidar Scan/Lidar_Scan.entitlements
